export interface Project {
  id: string;
  num: string;
  year: string;
  title: string;
  titleAccent: string;
  blurb: string;
  role: string;
  tags: string[];
  type: 'web' | 'ui';
  palette: [string, string, string];
  mascot: MascotName;
  summary: string;
  detail: string;
  stack: string[];
  timeline: string;
  image?: string;
  url?: string;
  screens?: { device: 'desktop' | 'tablet' | 'mobile'; image: string }[];
}

export type MascotName = 'pebble' | 'droplet' | 'splat' | 'star' | 'ring' | 'squiggle' | 'noodle';

export const PROJECTS: Project[] = [
  {
    id: 'bi-winning',
    num: '08',
    year: '2025',
    title: 'Bi-Winning',
    titleAccent: 'trading',
    blurb: 'Multilingual binary options trading platform — Japanese, English, Vietnamese, and Indonesian markets.',
    role: 'Design + build',
    tags: ['wordpress', 'php', 'multilingual'],
    type: 'web',
    palette: ['#1A1108', '#2D1E05', '#C9A227'],
    mascot: 'pebble',
    summary: 'Full marketing and onboarding site for a binary options broker targeting four Asian markets. Language picker on first visit, live market data widgets, account opening flow, and a news section for regulatory disclosures.',
    detail: 'Custom WordPress theme with a multilingual routing layer for JP, EN, VI, and ID. Dark amber aesthetic built to hold attention against live data widgets. Account opening CTA surfaces in the nav, hero, and footer. News section handles compliance announcements by locale.',
    stack: ['WordPress', 'PHP', 'MySQL', 'Cloudflare'],
    timeline: 'Client work',
    image: '/assets/projects/bi-winning.jpg',
    url: 'https://bi-winning.org',
  },
  {
    id: 'rc-wallet',
    num: '09',
    year: '2024',
    title: 'RC',
    titleAccent: 'Wallet',
    blurb: 'Landing page and user guide for a crypto-to-fiat exchange wallet — clean dark aesthetic, app download CTAs.',
    role: 'Design + build',
    tags: ['next.js', 'crypto', 'landing page'],
    type: 'web',
    palette: ['#0A0804', '#1A1510', '#BF9040'],
    mascot: 'ring',
    summary: 'Landing page, user guide, and glossary for a crypto-to-fiat wallet app. Minimal type-led design with prominent app download links and a structured guide section for onboarding new users.',
    detail: 'Statically generated Next.js site. Dark near-black with gold accents tracking the app brand. Phone mockup in the hero shows the wallet interface. Guide section structured as a flat MDX hierarchy — no CMS, fast deploys.',
    stack: ['Next.js', 'Figma', 'Vercel'],
    timeline: 'Client work',
    image: '/assets/projects/rc-wallet.jpg',
    url: 'https://rc-wallet.io',
  },
  {
    id: 'tenmixer',
    num: '10',
    year: '2024',
    title: 'Ten',
    titleAccent: 'Mixer',
    blurb: 'Cross-chain crypto mixer — incognito transactions across Bitcoin, Ethereum, Arbitrum, and more.',
    role: 'Design + build',
    tags: ['next.js', 'web3', 'crypto'],
    type: 'web',
    palette: ['#040A06', '#081508', '#00CC6A'],
    mascot: 'noodle',
    summary: 'Marketing site for a cross-chain privacy transaction tool. Dark green tech aesthetic, orbital coin visualization showing supported chains, and wallet connect entry point.',
    detail: 'Custom SVG orbital animation for the chain visualization — each coin orbiting a central mixer icon. Dark near-black with green accent. Wallet connect CTA, status page link for uptime transparency, and a cross-chain bridge section.',
    stack: ['Next.js', 'React', 'Web3.js', 'Figma'],
    timeline: 'Client work',
    image: '/assets/projects/tenmixer.jpg',
    url: 'https://tenmixer.com',
  },
  {
    id: 'edge-graph',
    num: '11',
    year: '2024',
    title: 'EdgeGraph',
    titleAccent: 'FX',
    blurb: 'Corporate site for a Japanese FX broker — bilingual JP/EN, account opening flow, market commentary.',
    role: 'Design + build',
    tags: ['wordpress', 'fx', 'multilingual'],
    type: 'web',
    palette: ['#F5F3F0', '#E8E0D8', '#CC1A1A'],
    mascot: 'star',
    summary: 'Full corporate and onboarding site for a licensed Japanese FX broker. Bilingual JP/EN, with account opening as the primary conversion goal and a market commentary section for returning traders.',
    detail: 'Bilingual toggle at nav level with Japanese as default. Light corporate palette with red accents for CTAs. Account opening button is persistent in the sticky nav. Market commentary section with filterable tabs for news and analysis.',
    stack: ['WordPress', 'PHP', 'MySQL', 'Cloudflare'],
    timeline: 'Client work',
    image: '/assets/projects/edge-graph.jpg',
    url: 'https://edge-graph.com',
  },
  {
    id: 'yumami',
    num: '12',
    year: '2026',
    title: 'Yumami',
    titleAccent: 'bento',
    blurb: 'Brand and e-commerce site for a Manila bento atelier — bold editorial type, online ordering, news.',
    role: 'Design + build',
    tags: ['next.js', 'e-commerce', 'restaurant'],
    type: 'web',
    palette: ['#F5C800', '#D4B000', '#1A1814'],
    mascot: 'splat',
    summary: 'Brand site and online ordering platform for Yumami, a bento atelier in BGC, Taguig. Bold yellow editorial design, chef recommendation card, live stats, and a news section for location announcements.',
    detail: 'Type-driven layout with a serif/italic headline and a "crossed out care, replaced with love" copywriting treatment. Chef recommendation card surfaces the daily pick dynamically. Stats block shows bento count, prep window, and hand-packed guarantee. News section tied to location expansion announcements.',
    stack: ['Next.js', 'Figma', 'Vercel', 'Netlify'],
    timeline: 'Client work',
    image: '/assets/projects/yumami.jpg',
    url: 'https://yumami-ph.netlify.app',
  },
  {
    id: 'wagyufive',
    num: '13',
    year: '2024',
    title: 'Wagyu',
    titleAccent: 'Five',
    blurb: 'Online store for a Manila wagyu delivery brand — product catalog, checkout, Metro Manila delivery.',
    role: 'Design + build',
    tags: ['shopify', 'e-commerce', 'food'],
    type: 'web',
    palette: ['#1A0E08', '#2D180E', '#C4956A'],
    mascot: 'droplet',
    summary: 'E-commerce store for a premium Japanese wagyu delivery brand serving Metro Manila. Dark food photography aesthetic, product catalog with marbling grade detail, and a checkout covering delivery zones.',
    detail: 'Shopify storefront with a fully custom theme. Full-bleed hero anchored in food photography. Product cards surface marbling grade and cut type. Delivery zone logic restricts checkout by barangay. Dark near-black with cream accents — keeping the premium positioning intact.',
    stack: ['Shopify', 'Liquid', 'Figma'],
    timeline: 'Client work',
    image: '/assets/projects/wagyufive.jpg',
    url: 'https://wagyufive.com',
  },
  {
    id: 'dxpcorp',
    num: '14',
    year: '2023',
    title: 'DXP',
    titleAccent: 'corp',
    blurb: 'Corporate site for a Japan-based web consultancy — services, process, company, and inquiry flow.',
    role: 'Design + build',
    tags: ['next.js', 'corporate', 'japan'],
    type: 'web',
    palette: ['#F0EEFF', '#DDD4FF', '#6B21E8'],
    mascot: 'squiggle',
    summary: 'Corporate and lead-gen site for DXP, a Japan-based web consultancy offering social media marketing, SEO, video production, and web development to Japanese businesses.',
    detail: 'Clean white with purple accents throughout. Services grid, process walkthrough, company overview, and a contact/inquiry form. Downloadable company profile PDF. Floating ball animations in the hero for visual energy without overloading the layout.',
    stack: ['Next.js', 'Figma', 'Vercel'],
    timeline: 'Client work',
    image: '/assets/projects/dxpcorp.jpg',
    url: 'https://dxpcorp.com',
  },
  {
    id: 'gaozap',
    num: '15',
    year: '2023',
    title: 'Gaozap',
    titleAccent: 'store',
    blurb: 'Japanese gadget e-commerce store — full catalog, category pages, brand pages, and flash sales.',
    role: 'Design + build',
    tags: ['shopify', 'e-commerce', 'japan'],
    type: 'web',
    palette: ['#FAFAFA', '#F0EDE8', '#E07B10'],
    mascot: 'star',
    summary: 'Full e-commerce store for Gaozap, a Singapore-based gadget and electronics retailer targeting the Japanese market. Hero carousel, product catalog, category navigation, brand landing pages, and flash sale promotions.',
    detail: 'Hero carousel for rotating promotions with countdown timers for flash sales. Product grid with sale badges, brand logos, and category filters. Brand landing pages for major electronics suppliers. Mobile-first layout aligned with Japanese shopping behavior.',
    stack: ['Shopify', 'Liquid', 'Custom Theme'],
    timeline: 'Client work',
    image: '/assets/projects/gaozap.jpg',
    url: 'https://gaozap.com',
  },
  {
    id: 'capsule-recruit',
    num: '16',
    year: '2023',
    title: 'Capsule',
    titleAccent: 'recruit',
    blurb: 'Talent recruitment platform for a Japanese agency — compliance pages, LINE integration, inquiry flow.',
    role: 'Design + build',
    tags: ['wordpress', 'recruitment', 'japan'],
    type: 'web',
    palette: ['#0A1F14', '#122D1E', '#00BB8A'],
    mascot: 'ring',
    summary: 'Recruitment site for Capsule Agency, a Japanese talent management agency. Compliance-first design with a detailed requirements flow, LINE integration for direct applicant contact, and a structured FAQ.',
    detail: 'Age-gated entry with a consent modal on load. LINE QR code integration for direct contact — primary conversion channel for this audience. Requirements, compliance, and FAQ pages with legally mandated disclosures. Interview flow section walks applicants through the four-step process. Mobile-optimized throughout.',
    stack: ['WordPress', 'PHP', 'LINE API'],
    timeline: 'Client work',
    image: '/assets/projects/capsule-recruit.jpg',
    url: 'https://recruit.capsule.bz',
  },
  {
    id: 'yumami-ux',
    num: '17',
    year: '2026',
    title: 'Yumami',
    titleAccent: 'UI / UX',
    blurb: 'Responsive UI/UX design for Yumami — desktop, tablet, and mobile layouts built in Figma before the build.',
    role: 'UI / UX design',
    tags: ['figma', 'ui design', 'responsive'],
    type: 'ui',
    palette: ['#F5C800', '#D4B000', '#1A1814'],
    mascot: 'splat',
    summary: 'Full UI/UX design for the Yumami bento brand site — desktop, tablet, and mobile. The design system centers on a bold yellow palette, Fraunces serif for editorial headlines, and a layout that leads with food photography and brand voice. Built in Figma across three breakpoints before any code was written.',
    detail: 'Desktop layout prioritizes the hero typographic treatment and full-width food imagery. Tablet compresses the two-column sections into a readable single-column flow without losing the editorial rhythm. Mobile-first grid tightens the chef card, stats strip, and ordering CTA into thumb-friendly zones. Type scale, spacing, and color tokens were defined upfront so the build could match the design exactly — no drift.',
    stack: ['Figma'],
    timeline: 'Client work',
    image: '/assets/projects/yumami.jpg',
    url: 'https://yumami-ph.netlify.app',
    screens: [
      { device: 'desktop', image: '/assets/yumami-desktop.png' },
      { device: 'mobile',  image: '/assets/yumami-mobile.png'  },
    ],
  },
];

export const MASCOT_PATHS: Record<MascotName, { vb: string; d: string; stroke?: number; fillRule?: 'evenodd' | 'nonzero' }> = {
  pebble:   { vb: '0 0 200 180', d: 'M28 92 C24 52, 64 14, 112 18 C158 22, 184 56, 178 100 C172 144, 134 168, 92 162 C50 156, 32 132, 28 92 Z' },
  droplet:  { vb: '0 0 160 220', d: 'M80 8 C46 56, 22 102, 22 142 C22 184, 48 212, 80 212 C112 212, 138 184, 138 142 C138 102, 114 56, 80 8 Z' },
  splat:    { vb: '0 0 220 220', d: 'M110 18 C128 28, 138 8, 158 22 C178 36, 168 60, 188 72 C208 84, 212 112, 192 128 C172 144, 184 168, 162 184 C140 200, 122 184, 104 196 C86 208, 64 200, 56 178 C48 156, 22 156, 18 134 C14 112, 38 102, 32 80 C26 58, 50 44, 64 30 C78 16, 92 8, 110 18 Z' },
  star:     { vb: '0 0 200 200', d: 'M100 12 C112 60, 144 64, 180 76 C148 100, 148 132, 162 180 C124 158, 96 160, 60 188 C68 144, 50 124, 16 96 C58 92, 76 64, 100 12 Z' },
  ring:     { vb: '0 0 200 200', d: 'M100 20 C148 20, 180 60, 180 100 C180 144, 144 180, 100 180 C56 180, 20 144, 20 100 C20 60, 52 20, 100 20 Z M100 60 C72 60, 60 80, 60 100 C60 124, 76 140, 100 140 C124 140, 140 124, 140 100 C140 80, 128 60, 100 60 Z', fillRule: 'evenodd' },
  squiggle: { vb: '0 0 260 80',  d: 'M8 40 C28 8, 56 8, 76 40 C96 72, 124 72, 144 40 C164 8, 192 8, 212 40 C232 72, 252 64, 252 40', stroke: 14 },
  noodle:   { vb: '0 0 240 120', d: 'M20 60 C20 30, 60 30, 60 60 C60 90, 100 90, 100 60 C100 30, 140 30, 140 60 C140 90, 180 90, 180 60 C180 30, 220 30, 220 60', stroke: 22 },
};

export const NAV_ITEMS = [
  { id: 'home',       href: '/',           num: '01', en: 'Home',       ta: 'Tahanan' },
  { id: 'works',      href: '/works',       num: '02', en: 'Works',      ta: 'Mga Gawa' },
  { id: 'about',      href: '/about',       num: '03', en: 'About',      ta: 'Tungkol' },
  { id: 'playground', href: '/playground',  num: '04', en: 'Playground', ta: 'Palaruan' },
  { id: 'contact',    href: '/contact',     num: '05', en: 'Contact',    ta: 'Ugnayan' },
] as const;
